{% set name = "pycnite" %}
{% set version = "2024.5.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycnite-{{ version }}.tar.gz
  sha256: 825949037eba62a6c46a22c998ea8be83d0136ca5297d30ec6941b886af34628

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8

test:
  imports:
    - pycnite
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/pycnite
  summary: Python bytecode utilities
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/google/pycnite
  doc_url: https://github.com/google/pycnite/

extra:
  recipe-maintainers:
    - ngam
