{% set name = "pycnite" %}
{% set version = "2024.6.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycnite-{{ version }}.tar.gz
  sha256: 301c5d7e2e2f61e5535d0af7c4486f3ea4f5083c4808a7645a55ddb45cb25027

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8

test:
  imports:
    - pycnite
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/pycnite
  summary: Python bytecode utilities
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/google/pycnite
  doc_url: https://github.com/google/pycnite/

extra:
  recipe-maintainers:
    - ngam
